config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#index'
  resources :users, only: %i[edit update show]
  resources :rooms do
    resources :categories
    resources :tasks do
      member do
        patch :complete
        patch :unfinished
      end
      collection do
        get 'search'
        get 'week'
      end
      resources :comments, only: %i[create destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :room
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :user

  validates :comment, presence: true
end

app/models/owner.rb
class Owner < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_one :owner, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :categories, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :room
  belongs_to :user
  belongs_to :edit_user, class_name: 'User'
  belongs_to :category
  has_many :comments, dependent: :destroy

  with_options presence: true do
    validates :task_name
    validates :start_time
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX, message: 'は半角英数を両方含む必要があります' }, on: :create

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :owners
  has_many :tasks
  has_many :comments
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  def index
    @room = Room.find(params[:room_id])
    @categories = @room.categories.includes(:room)
    @category = Category.new
  end

  def create
    @room = Room.find(params[:room_id])
    @category = @room.categories.new(category_params)

    if @category.save
      redirect_to room_categories_path(@room.id)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to room_categories_path(@room.id)
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to room_categories_path(@room.id)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @room = Room.find(params[:room_id])
    @category = @room.categories.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @task = Task.find(params[:task_id])
    @comment = @task.comments.new(comment_params)
    @comment.save
    redirect_to room_task_path(@task.room_id, @task.id)
  end

  def destroy
    @task = Task.find(params[:task_id])
    @comment = @task.comments.find(params[:id])
    @comment.destroy
    redirect_to room_task_path(@task.room_id, @task.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, task_id: @task.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[edit show update destroy]

  def index
    @rooms = Room.includes(:user)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)

    if @room.save
      Owner.create(name: current_user.nickname, user_id: current_user.id, room_id: @room.id)
      Category.create(name: '---', room_id: @room.id)
      redirect_to room_tasks_path(@room.id)
    else
      render :new
    end
  end

  def show
    @owner = Owner.where(room_id: @room.id).first
  end

  def edit; end

  def update
    if @room.update(room_params)
      redirect_to room_path(@room.id)
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end

  def set_room
    @room = Room.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_room, only: %i[show edit update destroy unfinished complete]
  before_action :set_beginning_of_week
  def index
    @task = Task.new
    @room = Room.find(params[:room_id])
    # @tasks = @room.tasks.includes(:user)
    @q = @room.tasks.ransack(params[:q])
    @tasks = @q.result.includes(:user)
  end

  def week
    @task = Task.new
    @room = Room.find(params[:room_id])
    # @tasks = @room.tasks.includes(:user)
    @q = @room.tasks.ransack(params[:q])
    @tasks = @q.result.includes(:user)
  end

  def create
    @room = Room.find(params[:room_id])
    @task = @room.tasks.new(task_params)
    if @task.save
      redirect_to room_tasks_path(@room.id)
    else
      @task = @room.tasks.includes(:user)
      render :index
    end
  end

  def show
    @owner = Owner.where(room_id: @room.id).first
    @comment = Comment.new
    @comments = @task.comments.includes(:user)
  end

  def edit; end

  def update
    if @task.update(task_edit_params)
      redirect_to room_tasks_path(@room.id)
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to room_tasks_path(@room.id)
  end

  def unfinished
    @task.update(is_completed: true)
    redirect_to room_tasks_path(@room.id)
  end

  def complete
    @task.update(is_completed: false)
    redirect_to room_tasks_path(@room.id)
  end

  def search
    @q = Task.ransack(params[:q])
    @tasks = @q.result
  end

  private

  def task_params
    params.require(:task).permit(:task_name, :content, :start_time, :is_completed,
                                 :category_id).merge(user_id: current_user.id, edit_user_id: current_user.id)
  end

  def task_edit_params
    params.require(:task).permit(:task_name, :content, :start_time, :is_completed,
                                 :category_id, :user_id).merge(edit_user_id: current_user.id)
  end

  def set_room
    @room = Room.find(params[:room_id])
    @task = @room.tasks.find(params[:id])
  end

  def set_beginning_of_week
    Date.beginning_of_week = :sunday
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit; end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @nickname = current_user.nickname
    @rooms = current_user.rooms
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/completes_helper.rb
module CompletesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class= "header bg-dark mx-auto">
  <nav class="navbar navbar-expand navbar-light text-center">
    <div class="container-fluid flex-column">
      <div class="collapse navbar-collapse col" id="navbarNav">
      <li class="nav-item ">
        <%= link_to "タスクマネージャー", root_path, class: "navbar-brand text-white"  %>
      </li>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_header.html.erb
<div class= "header bg-dark">
  <nav class="navbar navbar-expand navbar-light ">
    <div class="container-fluid ">
      <% if defined?(@room) && @room && !action_name.eql?("new") %>
      <%= link_to @room.name, room_path(@room.id), class: "navbar-brand text-white"  %>
      <% else %>
      <%= link_to "タスクマネージャー", root_path, class: "navbar-brand text-white"  %>
      <% end %>
      <div class="collapse navbar-collapse " id="navbarNav">
        <ul class="navbar-nav ms-auto hamburger">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to current_user.nickname, user_path(current_user.id), class: "nav-link text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to 'ルーム作成', new_room_path, class: "nav-link text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link text-white" %>
            </li>
            <% if defined?(@room) && @room && !action_name.eql?("new") %>
              <li class="nav-item">
                <%= link_to 'ルーム', room_tasks_path(@room.id), class: "nav-link text-white" %>
              </li>
              <li class="nav-item">
                <%= link_to 'カテゴリー', room_categories_path(@room.id), class: "nav-link text-white" %>
              </li>
            <% end %>
          <% else %>
          <li class="nav-item">
            <%= link_to 'ログイン', new_user_session_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to '新規登録', new_user_registration_path, class: "nav-link text-white" %>
          </li>
          <% end %>
        </ul>
      </div>
      <div class="burger">
        <div class="line1"></div>
        <div class="line2"></div>
        <div class="line3"></div>
      </div>
    </div>
  </nav>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar ">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '先月'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '次月'), calendar.url_for_next_view %>
    <%= link_to "週", week_room_tasks_path(@room.id), method: :get, class: "ps-3 btn btn-outline-dark"  %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '先週'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: '次週'), calendar.url_for_next_view %>
    <%= link_to "月", room_tasks_path(@room.id), method: :get, class: "ps-3 btn btn-outline-dark"  %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>