config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#index'
  resources :users, only: %i[edit update show]
  resources :rooms do
    resources :categories
    resources :tasks do
      member do
        patch :complete
        patch :unfinished
      end
      collection do
        get 'search'
        get 'week'
      end
      resources :comments, only: %i[create destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :room
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :user

  validates :comment, presence: true
end

app/models/owner.rb
class Owner < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_one :owner, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :categories, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :room
  belongs_to :user
  belongs_to :edit_user, class_name: 'User'
  belongs_to :category
  has_many :comments, dependent: :destroy

  with_options presence: true do
    validates :task_name
    validates :start_time
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX, message: 'は半角英数を両方含む必要があります' }, on: :create

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :owners
  has_many :tasks
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  def index
    @room = Room.find(params[:room_id])
    @categories = @room.categories.includes(:room)
    @category = Category.new
  end

  def create
    @room = Room.find(params[:room_id])
    @category = @room.categories.new(category_params)

    if @category.save
      redirect_to room_categories_path(@room.id)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to room_categories_path(@room.id)
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to room_categories_path(@room.id)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @room = Room.find(params[:room_id])
    @category = @room.categories.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @task = Task.find(params[:task_id])
    @comment = @task.comments.new(comment_params)
    @comment.save
    redirect_to room_task_path(@task.room_id, @task.id)
  end

  def destroy
    @task = Task.find(params[:task_id])
    @comment = @task.comments.find(params[:id])
    @comment.destroy
    redirect_to room_task_path(@task.room_id, @task.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, task_id: @task.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[edit show update destroy]

  def index
    @rooms = Room.includes(:user)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)

    if @room.save
      Owner.create(name: current_user.nickname, user_id: current_user.id, room_id: @room.id)
      Category.create(name: '---', room_id: @room.id)
      redirect_to room_tasks_path(@room.id)
    else
      render :new
    end
  end

  def show
    @owner = Owner.where(room_id: @room.id).first
  end

  def edit; end

  def update
    if @room.update(room_params)
      redirect_to room_path(@room.id)
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end

  def set_room
    @room = Room.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_room, only: %i[show edit update destroy unfinished complete]
  before_action :set_beginning_of_week
  def index
    @task = Task.new
    @room = Room.find(params[:room_id])
    # @tasks = @room.tasks.includes(:user)
    @q = @room.tasks.ransack(params[:q])
    @tasks = @q.result.includes(:user)
  end

  def week
    @task = Task.new
    @room = Room.find(params[:room_id])
    # @tasks = @room.tasks.includes(:user)
    @q = @room.tasks.ransack(params[:q])
    @tasks = @q.result.includes(:user)
  end

  def create
    @room = Room.find(params[:room_id])
    @task = @room.tasks.new(task_params)
    if @task.save
      redirect_to room_tasks_path(@room.id)
    else
      @task = @room.tasks.includes(:user)
      render :index
    end
  end

  def show
    @owner = Owner.where(room_id: @room.id).first
    @comment = Comment.new
    @comments = @task.comments.includes(:user)
  end

  def edit; end

  def update
    if @task.update(task_edit_params)
      redirect_to room_tasks_path(@room.id)
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to room_tasks_path(@room.id)
  end

  def unfinished
    @task.update(is_completed: true)
    redirect_to room_tasks_path(@room.id)
  end

  def complete
    @task.update(is_completed: false)
    redirect_to room_tasks_path(@room.id)
  end

  def search
    @q = Task.ransack(params[:q])
    @tasks = @q.result
  end

  private

  def task_params
    params.require(:task).permit(:task_name, :content, :start_time, :is_completed,
                                 :category_id).merge(user_id: current_user.id, edit_user_id: current_user.id)
  end

  def task_edit_params
    params.require(:task).permit(:task_name, :content, :start_time, :is_completed,
                                 :category_id, :user_id).merge(edit_user_id: current_user.id)
  end

  def set_room
    @room = Room.find(params[:room_id])
    @task = @room.tasks.find(params[:id])
  end

  def set_beginning_of_week
    Date.beginning_of_week = :sunday
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit; end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @nickname = current_user.nickname
    @rooms = current_user.rooms
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/completes_helper.rb
module CompletesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/edit.html.erb
<%= render "shared/header" %>
<div class="main gr-categories-edit pt-5">
  <div class="w-50 h-75 m-auto text-center mt-5 mb-5 rounded-3 bg-light overflow-auto">
    <div class="room-name my-3 text-center">
      <div class="text-center d-flex flex-column justify-content-center align-items-center p-2">
      <%= form_with model: [@room, @category], class: 'form', id: "form" do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
        <div class="pt-3">
          <%= f.label :カテゴリー名, class: 'lavel ' %>
          <%= f.text_field :name, class: 'form-control ' %>
        </div>
        <div class="mt-3">
          <%= f.submit '保存',class: "mt-3" %>
        </div>
      <% end %>
    </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/categories/index.html.erb
<%= render "shared/header" %>
<div class="main gr-categories-show pt-5">
  <div class="w-75 h-75 m-auto text-center mt-5 mb-5 rounded-3 bg-light overflow-auto">
  <div class="room-name my-3 text-center">
    <%= link_to "#{@room.name}詳細へ", room_path(@room.id),  class: "text-decoration-none text-white btn btn-secondary" %>
  </div>
<div class="text-center d-flex flex-column justify-content-center align-items-center p-2">
  <%= form_with model: [@room, @category], class: 'form', id: "form" do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
  <div class="mt-3">
    <%= f.label :カテゴリー名, class: 'lavel ' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
    <div class="mt-3">
    <%= f.submit '保存',class: "mt-3" %>
    </div>
  <% end %>

  <div class= "mt-5 ">
    <h2>カテゴリー一覧</h2>
    <% @categories.each do |category| %>
    <% if category.room_id == @room.id %>
    <div class="mt-3 d-flex ">
      <div class="me-5"> 
        <h5>
        <%= category.name %>
        </h5>
      </div>
     <%= link_to "カテゴリーの編集", edit_room_category_path(category.room_id, category.id), method: :get, class:"me-2 text-decoration-none text-primary"  %>
      <p class="">or</p>
      <%= link_to "削除", room_category_path(category.room_id, category.id), method: :delete, class:"ms-2 text-decoration-none text-danger", data: {confirm: "カテゴリーを削除しますか？"} %>
     <% end %>
    </div>
    <% end %>
  </div>
</div>
</div>
</div>
<%= render "shared/footer" %>

app/views/rooms/edit.html.erb
<%= render "shared/header" %>
<div class="main gr-edit pt-5">
<div class="main d-flex justify-content-center bg-primary w-50 h-75 m-auto text-center  rounded-3 bg-light overflow-auto">
<div class='chat-room-form pt-5'>
  <h1>ルーム編集</h1>
  <%=form_with model: @room, local: true do |f|%>
    <%= render 'shared/error_messages', model: f.object %>
    <div class='chat-room-form__field mt-5'>
      <div class='chat-room-form__field--left'>
        <%= f.label :name, :ルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field overflow-x-auto'>
      <div class='chat-room-form__field--left mt-5'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right mt-3'>
        <% User.where.not(id: current_user.id).each do |user| %>
          <label>
            <%= check_box_tag "room[user_ids][]", user.id, @room.users.include?(user), id: "user_#{user.id}"  %>
            <%= user.nickname %>
          </label>
        <% end %>
        <%= hidden_field_tag "room[user_ids][]", current_user.id %>
        <%= hidden_field_tag "room_usre[create_user_ids][]", current_user.id %>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <div class="text-danger">自動的に作成者はルームに参加します</div>
        <%= f.submit "ルーム作成", class: 'btn btn-primary mt-5'%>
      </div>
    </div>
  <% end %>
</div>
</div>
</div>
<%= render "shared/footer" %>

app/views/rooms/index.html.erb
<%= render "shared/header" %>
<div class="main text-center gr">
  <% if user_signed_in? %>
  <h1 class="text-dark">参加しているルーム</h1>
    <% current_user.rooms.each do |room| %>
      <div class="room">
        <div class="room-name mb-3 ">
          <%= link_to room.name, room_tasks_path(room.id),  class: "text-decoration-none text-white btn btn-secondary" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<%= render "shared/footer" %>

app/views/rooms/new.html.erb
<%= render "shared/header" %>
<div class="main gr-new p-2" >
  <div class="d-flex justify-content-center  w-50 h-75 m-auto text-center mt-5 mb-5 rounded-3 bg-light overflow-auto">
  <div class='chat-room-form pt-5'>
    <h1>新規ルーム作成</h1>
    <%=form_with model: @room, local: true do |f|%>
      <%= render 'shared/error_messages', model: f.object %>
      <div class='chat-room-form__field mt-5'>
        <div class='chat-room-form__field--left'>
          <%= f.label :name, :ルーム名, class: 'chat-room-form__label'%>
        </div>
        <div class='chat-room-form__field--right'>
          <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'ルーム名を入力してください'%>
        </div>
      </div>
      <div class='chat-room-form__field'>
      </div>
      <div class='chat-room-form__field overflow-x-auto'>
        <div class='chat-room-form__field--left mt-5'>
          <label class='chat-room-form__label' for='chat_room_ルームメンバー'>ルームメンバー</label>
        </div>
        <div class='chat-room-form__field--right mt-3'>
          <% User.where.not(id: current_user.id).each do |user| %>
            <label>
              <%= check_box_tag "room[user_ids][]", user.id %>
              <%= user.nickname %>
            </label>
          <% end %>
          <%= hidden_field_tag "room[user_ids][]", current_user.id %>
          <%= hidden_field_tag "room_usre[create_user_ids][]", current_user.id %>
        </div>
      </div>
      <div class='chat-room-form__field'>
        <div class='chat-room-form__field--left'></div>
        <div class='chat-room-form__field--right'>
          <div class="text-danger">自動的に作成者はルームに参加します</div>
          <%= f.submit "ルーム作成", class: 'btn btn-primary mt-5'%>
        </div>
      </div>
    <% end %>
  </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/rooms/show.html.erb
<%= render "shared/header" %>
<div class="main text-center pt-5 gr-show">
  <div class="w-50 m-auto bg-light  text-align-center  rounded-3 overflow-auto">
    <%= link_to room_tasks_path(@room.id),  class: "text-body btn " do %>
    <h1><%= @room.name %></h1>
    
        <div class="room">
          <div class="room-name mb-3">
            <h5>参加者</h5>
            <% @room.users.where.not(id: current_user.id).each do |user| %>
              <p><%= user.nickname %>さん</p>
            <% end %>
          </div>
        </div>
        <div>
          
            <h5>作成者</h5>
            <p><%= @owner.name %></p>
          
          </div>
          
          
          <% end %>
          <div>
            <% if user_signed_in? && current_user.id == @owner.user.id %>
            <%= link_to "ルームの編集", edit_room_path(@room.id), method: :get, class:"btn btn-primary"  %>
            <p class="or-text mt-3">or</p>
            <%= link_to "削除", room_path(@room.id), method: :delete, class:"btn btn-danger", data: {confirm: "ルームを削除しますか？"} %>
            <% end %>
          </div>
          <div class="my-5">
          <%= link_to "カテゴリーの一覧", room_categories_path(@room.id), method: :get, class:"btn btn-success"  %>
          </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/tasks/edit.html.erb
<%= render "shared/header" %>
<div class="main gr-task-edit pt-3">
  <div class="d-flex justify-content-center bg-primary w-50 h-75 m-auto text-center mt-5 mb-5 rounded-3 bg-light overflow-auto">
    <div class='chat-room-form pt-5'>
      <h1>タスク編集</h1>
        <%=form_with model: [@room, @task], local: true do |f|%>
            <%= render 'shared/error_messages', model: f.object %>
            <div>
            <%= f.label :日付を選択, class: 'lavel' %>
            <%= f.date_field :start_time, class: 'form-control' %>
          </div>
          <div class="mt-3">
            <%= f.label :タスク名, class: 'lavel ' %>
            <%= f.text_field :task_name, class: 'form-control' %>
          </div>
            <div class="mt-3">
              <%= f.label :タスク詳細, class: 'lavel' %>
              <%= f.text_area :content, class: 'form-control' %>
            </div>
            <div class="mt-3"> 
              <%= f.label :カテゴリー, class: 'lavel' %>
              <%= f.collection_select(:category_id, Category.where(room_id: params[:room_id]), :id, :name, {}, {class:"select-box", id:"item-category"}) %> 
            </div>
            <%= f.submit '保存', class: "mt-3 mb-3" %>
        <% end %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/tasks/index.html.erb
<%= render "shared/header" %>
<div class="main room-name mb-3 overflow-auto mt-3">
  
  <div class="room-name mb-3 text-center">
    <%= link_to "#{@room.name}詳細へ", room_path(@room.id),  class: "text-decoration-none text-white btn btn-secondary" %>
  </div>
  <div class="text-center d-flex justify-content-center p-2">
    <%= form_with model: [@room, @task], class: 'form', id: "form" do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <div>
        <%= f.label :日付を選択, class: 'lavel' %>
        <%= f.date_field :start_time, class: 'form-control' %>
      </div>
      <div class="mt-3">
        <%= f.label :タスク名, class: 'lavel ' %>
        <%= f.text_field :task_name, class: 'form-control' %>
      </div>
      <div class="mt-3">
        <%= f.label :タスク詳細, class: 'lavel' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <div class="mt-3"> 
        <%= f.label :カテゴリー, class: 'lavel' %>
        <%= f.collection_select(:category_id, Category.where(room_id: params[:room_id]), :id, :name, {}, {class:"select-box", id:"item-category"}) %> 
      </div>
    
      <div class="mt-3">
      <%= f.submit '保存', id: "task_submit"%>
      </div>
    <% end %>
  </div>
  
  
  <div class="text-center mx-auto my-5 mb-5  w-50 ">
    <%= search_form_for Task.ransack(params[:q]), url: room_tasks_path(@room.id), html: {class: "search-form"} do |f| %>
      <div class="search-field mb-3 p-2">
        <%= f.label :category_id_in, 'カテゴリー検索', class: "mb-2" %>
        <br>
        <%= f.collection_check_boxes(:category_id_in, Category.where(room_id: params[:room_id]), :id, :name, {}, {class: "ms-4"}) %>
      </div>
      <div>
        <input type="submit" value="検索" class="send mb-3">
        <%= f.submit :submit, id: "q_submit", style: "display: none;"%>
      </div>
    <% end %>
  </div>
  
  
  

      <div class="room m-auto w-75" id="month_calendar">
        <%= month_calendar events: @tasks do |date, tasks| %>
          <%= date.day %>
          <% tasks.each do |task| %>       
          <ul class ="list-unstyled task_ul ">
            <% if task.is_completed %>
                <li class="task_li task d-flex align-items-center">
                  <%= form_with url: complete_room_task_path(@room.id, task.id), method: :patch do |f| %>
                    <%= f.submit "完" %>
                  <% end %>
                  <%= link_to task.task_name, room_task_path(@room.id, task.id), method: :get, class: "text-decoration-none text-body task_completed ps-3 "  %>
                </li>
            <% else %>
                <li class="task_li d-flex align-items-center ">
                <%= form_with url: unfinished_room_task_path(@room.id, task.id), method: :patch do |f| %>
                  <%= f.submit "未" %>
                <% end %>
                <%= link_to task.task_name, room_task_path(@room.id, task.id), method: :get, class: "text-decoration-none text-body task_completed ps-3 "  %>
                </li>
            <% end %>
            </li>
          </ul>
          <% end %>
        <% end %>

      </div>

        
      </div>
      

      
      
</div>
<%= render "shared/footer" %>

app/views/tasks/show.html.erb
<%= render "shared/header" %>
<div class="main gr-task-show overflow-auto">
  <div class="text-center ">
    <div class="w-50 m-auto bg-light  text-align-center mt-5 rounded-3 mb-5">
      <%= link_to room_tasks_path(@task.room.id),  class: "text-body btn " do %>
      
      <h1 class="mt-3"><%= @task.task_name %></h1>
      
          <div class="room mt-4">
            <div class="room-name pb-3">
              <h5>詳細</h5>
              <%= @task.content %>
              <% if @task&.category.present? %>
                <h5 class="pt-3">カテゴリー</h5>
                <%= @task.category.name %>
              <% end %>
              <div class="p-2 <%= 'text-danger' if Date.parse(l(@task.start_time.to_date, format: :short)) < Date.current %>">
                <h5>予定日</h5>
                <p><%= l @task.start_time.to_date, format: :short %></p>
              </div>
            </div>
          </div>
          <h5>作成者</h5>
          <p><%= @task.user.nickname %></p>

          <% if @task.edit_user_id? %>
          <h5>編集者</h5>
          <p><%= @task.edit_user.nickname %></p>
          <p>編集日：<%= l @task.updated_at , format: :short%></p>
          <% end %>

        
          <p>完了状況：<%= @task.is_completed ? "完了" : "未完了" %></p>
          
  
    
            <% end %>
          <div>
            <div class="container">
              <% if user_signed_in? %>
              <%= form_with(model: [@room, @task, @comment], local: true) do |form| %>
                <%= form.text_area :comment %>
                <div class="my-5">
                <%= form.submit 'コメントを投稿', class:"btn btn-info" %>
              </div>
              <% end %>
              <% else %>
                <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
              <% end %>
            </div>

            
              <div class="comments p-2">
                <% if @comments.length > 0 %>
              <h4>＜コメント一覧＞</h4>
              <% @comments.each do |comment| %>
                <p>
                  <strong><%= comment.user.nickname%>：</strong>
                  <%= comment.comment %>
                  <%= l comment.created_at, format: :short %>
                  <% if user_signed_in? && current_user.id == comment.user.id %>
                    <%= link_to '削除', room_task_comment_path(@task.room_id, @task.id, comment.id), method: :delete, data: { confirm: 'コメントを削除しますか？' } %>
                  <% end %>
                </p>
                <% end %>
               <% end %>
            </div>
          
            

            <div class="w-50 m-auto bg-light  text-align-center mt-4  pb-5 rounded-3 ">
            <% if user_signed_in? && current_user.id == @task.user.id || user_signed_in? && current_user.id == @owner.user.id %>
              <%= link_to "タスクの編集", edit_room_task_path(@task.room_id, @task.id), method: :get, class:"btn btn-primary"  %>
              <p class="or-text mt-3">or</p>
              <%= link_to "タスクの削除", room_task_path(@task.room_id, @task.id), method: :delete, class:"btn btn-danger", data: {confirm: "タスクを削除しますか？"} %>
            <% end %>
            </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/tasks/week.html.erb
<%= render "shared/header" %>
<div class="main room-name mb-3 overflow-auto mt-3">
  
  <div class="room-name mb-3 text-center">
    <%= link_to "#{@room.name}詳細へ", room_path(@room.id),  class: "text-decoration-none text-white btn btn-secondary" %>
  </div>
  <div class="text-center d-flex justify-content-center p-2">
    <%= form_with model: [@room, @task], class: 'form', id: "form" do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <div>
        <%= f.label :日付を選択, class: 'lavel' %>
        <%= f.date_field :start_time, class: 'form-control' %>
      </div>
      <div class="mt-3">
        <%= f.label :タスク名, class: 'lavel ' %>
        <%= f.text_field :task_name, class: 'form-control' %>
      </div>
      <div class="mt-3">
        <%= f.label :タスク詳細, class: 'lavel' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <div class="mt-3"> 
        <%= f.label :カテゴリー, class: 'lavel' %>
        <%= f.collection_select(:category_id, Category.where(room_id: params[:room_id]), :id, :name, {}, {class:"select-box", id:"item-category"}) %> 
      </div>
    
      <div class="mt-3">
      <%= f.submit '保存', id: "task_submit"%>
      </div>
    <% end %>
  </div>
  
  
  <div class="text-center mx-auto my-5 mb-5  w-50 ">
    <%= search_form_for Task.ransack(params[:q]), url: room_tasks_path(@room.id), html: {class: "search-form"} do |f| %>
      <div class="search-field mb-3 p-2">
        <%= f.label :category_id_in, 'カテゴリー検索', class: "mb-2" %>
        <br>
        <%= f.collection_check_boxes(:category_id_in, Category.where(room_id: params[:room_id]), :id, :name, {}, {class: "ms-4"}) %>
      </div>
      <div>
        <input type="submit" value="検索" class="send mb-3">
        <%= f.submit :submit, id: "q_submit", style: "display: none;"%>
      </div>
    <% end %>
  </div>
  
  
  

<div class="room m-auto w-75" id="month_calendar">
        <%= week_calendar ({ number_of_weeks: 2, events: @tasks }) do |date, tasks| %>
          <%= date.day %>
          <% tasks.each do |task| %>       
          <ul class ="list-unstyled task_ul ">
            <% if task.is_completed %>
                <li class="task_li task d-flex align-items-center">
                  <%= form_with url: complete_room_task_path(@room.id, task.id), method: :patch do |f| %>
                    <%= f.submit "完" %>
                  <% end %>
                  <%= link_to task.task_name, room_task_path(@room.id, task.id), method: :get, class: "text-decoration-none text-body task_completed ps-3 "  %>
                </li>
            <% else %>
                <li class="task_li d-flex align-items-center ">
                <%= form_with url: unfinished_room_task_path(@room.id, task.id), method: :patch do |f| %>
                  <%= f.submit "未" %>
                <% end %>
                <%= link_to task.task_name, room_task_path(@room.id, task.id), method: :get, class: "text-decoration-none text-body task_completed ps-3 "  %>
                </li>
            <% end %>
            </li>
          </ul>
          <% end %>
        <% end %>



      </div>
    </div>
    <%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="main gr-users-edit pt-5 overflow-auto">
  <div class="w-50 m-auto bg-light  text-align-center  rounded-3 text-center">
    <% if user_signed_in? %>
    <div class="pt-3">
      <h1><%= current_user.nickname %></h1>
      <div class="mt-3">
        <h2>メールアドレス</h2>
        <%= current_user.email %>
      </div>
    </div>

    <div class="mt-5">
      <%= link_to "編集", edit_user_path(current_user.id), method: :get, class: "btn btn-primary" %>
    </div>


      <div class="py-5">
        <h3>参加しているルーム</h3>
          <% current_user.rooms.each do |room| %>
            <div class="room">
              <div class="room-name pb-3">
                <%= link_to room.name, room_tasks_path(room.id),  class: "text-decoration-none text-white btn btn-secondary" %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
          
  </div>
</div>
<%= render "shared/footer" %>